# Example configuration for RBAC Middleware
# Add this to your Home Assistant configuration.yaml

rbac:
  # No configuration needed here - all access control is defined in access_control.yaml

# Example automations using RBAC services

automation:
  # Reload RBAC configuration when needed
  - alias: "Reload RBAC Config"
    trigger:
      - platform: event
        event_type: rbac_config_changed
    action:
      - service: rbac.reload_config

  # Check user access on login
  - alias: "Check User Access on Login"
    trigger:
      - platform: event
        event_type: user_logged_in
    action:
      - service: rbac.get_user_config
        data:
          user_id: "{{ trigger.event.data.user_id }}"

# Example scripts using RBAC services

script:
  # Check user configuration
  check_user_config:
    alias: "Check User Configuration"
    sequence:
      - service: rbac.get_user_config
        data:
          user_id: "user-123"

  # List all configured users
  list_all_users:
    alias: "List All Users"
    sequence:
      - service: rbac.list_users

  # Reload configuration
  reload_rbac_config:
    alias: "Reload RBAC Configuration"
    sequence:
      - service: rbac.reload_config
      - service: notify.persistent_notification
        data:
          message: "RBAC configuration reloaded successfully"
          title: "RBAC Config Reloaded"
