get_user_config:
  name: Get user configuration
  description: Get the access control configuration for a specific user
  fields:
    person:
      name: Person
      description: The person entity to get configuration for
      required: true
      example: "person.john_doe"
      selector:
        entity:
          domain: person

reload_config:
  name: Reload configuration
  description: Reload the access control configuration from file (admin only)
  fields: {}

list_users:
  name: List users
  description: List all users configured in the access control system
  fields: {}

add_user:
  name: Add user
  description: Add a user to the access control system with a specific role (admin only)
  fields:
    person:
      name: Person
      description: The person entity to add to access control
      required: true
      example: "person.john_doe"
      selector:
        entity:
          domain: person
    role:
      name: Role
      description: The role to assign to the user
      required: true
      example: "admin"
      selector:
        text:

get_available_roles:
  name: Get available roles
  description: Get all available roles from access control configuration (admin only)
  fields: {}