#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

python3 -m pip install --requirement requirements.txt
sudo apt --assume-yes install nodejs
sudo apt --assume-yes install npm
sudo apt --assume-yes install sshpass

./scripts/deploy-frontend-devcontainer.sh